version: '3'

services:
  localstack:
    image: localstack/localstack:0.10.6
    hostname: localhost
    ports:
      - "4572:4572"
      - "4566:4566"
      - "4569:4569"
      - "4576:4576"
    environment:
      - SERVICES=s3,sqs,dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=1234
      - AWS_SECRET_ACCESS_KEY=1234
      - AWS_EXECUTION_ENV=True
      - HOSTNAME_EXTERNAL=localhost
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1

  postgres_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=local-db
    ports:
      - 5434:5432
    volumes:
      - "./docker-init-db-scripts:/docker-entrypoint-initdb.d"
      - "./postgres-data:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - default

#networks:
#  test:
#    driver: bridge
networks:
  default:
    external:
      name: localdev